RegisterServerEvent("mCore:RequestEmote")
AddEventHandler("mCore:RequestEmote", function(target, emoteanim, emotename)
	TriggerClientEvent("ClientEmoteRequestReceive", target, emoteanim, emotename)
end)

RegisterServerEvent("mCore:ValidServer") 
AddEventHandler("mCore:ValidServer", function(target, requestedemote)
	TriggerClientEvent("cAnimTaskAnimPlayer", source, requestedemote, true)
	TriggerClientEvent("cAnimTaskAnimPlayer", target, requestedemote, false)
end)